config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :prizes do
        resources :comments
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end

  namespace :api do
    namespace :v1 do
      resources :parents
    end
  end

  default_url_options :host => "http://localhost:3000"

  get 'welcome/index'
  root 'welcome#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :prize
end

app/models/parent.rb
class Parent < ApplicationRecord

  has_one_attached :avatar

  has_many :users
  has_many :prizes

  validates :googleid, presence: true

end

app/models/prize.rb
class Prize < ApplicationRecord

  has_one_attached :prizeimage

  belongs_to :parent

  validates :title, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  has_one_attached :avatar

  belongs_to :parent

  validates :name, presence: true


end

app/controllers/api/v1/parents_controller.rb
class Api::V1::ParentsController < ApplicationController


  def index
    @parents = Parent.with_attached_avatar.all
    render json: @parents
  end

  def new
    @parent = Parent.new
  end

  def edit
  @parent = Parent.find(params[:id])
end

  def create
    @parent = Parent.new(parent_params)

    @parent.errors.empty?
    puts @parent.errors.full_messages

    if @parent.save
      render json: @parents
    else
      render 'new'
    end
  end

  def show
    @parent = Parent.find(params[:id])
    render json: @parents
  end

  def update
  @parent = Parent.find(params[:id])

  if @parent.update(parent_params)
    @parent = Parent.find(params[:id])
    render json: @parents
  else
    render 'edit'
  end
end

def destroy
  @parent = Parent.find(params[:id])
  @parent.destroy

end

private
  def parent_params
    params.permit( :name, :avatar, :googleid, :parent)
  end

end

app/controllers/api/v1/prizes_controller.rb
class Api::V1::PrizesController < ApplicationController

  def index
    # @prizes = Prize.all
    @prizes = Prize.with_attached_prizeimage.all
    render json: @prizes
  end

  def new
    @prize = Prize.new
    render json: @prizes
  end

  def edit
  @prize = Prize.find(params[:id])
end

  def create
    @prize = Prize.new(prize_params)

    if @prize.save
        render json: @prizes
    else
      render 'new'
    end
  end

  def show
    @prize = Prize.find(params[:id])
    render json: @prizes
  end

  def update
  @prize = Prize.find(params[:id])

  if @prize.update(prize_params)
    render json: @prizes
  else
    render 'edit'
  end
end

def destroy
  @prize = Prize.find(params[:id])
  @prize.destroy

end

  private
  def prize_params
    params.permit(:title, :price, :prizeimage, :prize, :parent_id)
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController


  def index
    @users = User.with_attached_avatar.all
    render json: @users
  end

  def new
    @user = User.new
  end

  def edit
  @user = User.find(params[:id])
end

  def create
    @user = User.new(user_params)

    @user.errors.empty?
    puts @user.errors.full_messages

    if @user.save
      render json: @users
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    render json: @users
  end

  def update
  @user = User.find(params[:id])

  if @user.update(user_params)
    @user = User.find(params[:id])
    render json: @users
  else
    render 'edit'
  end
end

def destroy
  @user = User.find(params[:id])
  @user.destroy
end

private
  def user_params
    params.permit( :name, :avatar, :count, :id, :users, :user, :parent_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :null_session

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
    @prize = Prize.find(params[:prize_id])
    @comment = @prize.comments.create(comment_params)
    redirect_to prize_path(@prize)
  end

  def destroy
    @prize = Prize.find(params[:prize_id])
    @comment = @prize.comments.find(params[:id])
    @comment.destroy
    redirect_to prize_path(@prize)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/prizes_controller.rb
class PrizesController < ApplicationController



  def index
    @prizes = Prize.all
    # @prizes = Prize.with_attached_image.all
  # render json: @prizes.with_attached_image
    render json: @prizes
  end

  def new
    @prize = Prize.new
  end

  def edit
  @prize = Prize.find(params[:id])
end

  def create
    @prize = Prize.new(prize_params)

    if @prize.save
      render json: @prize
      redirect_to @prize
    else
      render 'new'
    end
  end

  def show
    @prize = Prize.find(params[:id])
    render json: @prizes
  end

  def update
  @prize = Prize.find(params[:id])

  if @prize.update(prize_params)
    redirect_to @prize
  else
    render 'edit'
  end
end

def destroy
  @prize = Prize.find(params[:id])
  @prize.destroy

  redirect_to prizes_path
end

  private
  def prize_params
    params.require(:prize).permit(:title, :text, :prizeimage)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    render json: @users
  end

  # def show
  #   @user = User.find(params[:id])
  #   render json: @users
  # end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.prize, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @prize, @prize.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChikettoB</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/prize/_form.html.erb
<%= form_with model: @prize, local: true do |form| %>

  <% if @prize.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@prize.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @prize.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :price %><br>
    <%= form.text_area :price %>
  </p>

  <p>
    <%= form.label :prizeimage %><br>
    <%= form.file_field :prizeimage %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/prize/create.html.erb
<h1>New Prize</h1>

<%= render 'form' %>

<%= link_to 'Back', prizes_path %>

app/views/prize/edit.html.erb
<h1>Edit Prize</h1>

<%= render 'form' %>

<%= link_to 'Back', prizes_path %>

app/views/prize/index.html.erb
<h1>Listing Prizes</h1>
<%= link_to 'New prize', new_prize_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th></th>
  </tr>

  <% @prizes.each do |prize| %>
    <tr>
      <td><%= prize.title %></td>
      <td><%= prize.price %></td>
      <td><%= link_to 'Show', prize_path(prize) %></td>
      <td><%= link_to 'Edit', edit_prize_path(prize) %></td>
      <td><%= link_to 'Destroy', prize_path(prize),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/prize/new.html.erb
<h1>New Prize</h1>

<%= render 'form' %>

<%= link_to 'Back', prizes_path %>

app/views/prize/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @prize.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @prize.price %>
</p>

<h2>Comments</h2>
<%= render @prize.comments %>


<%= image_tag(@prize.prizeimage, style:'width:20%') %>


<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_prize_path(@prize) %>
<%= link_to 'Back to Prizes', prizes_path %>

app/views/prizes/new.html.erb
<%= form_with scope: :prize, url: prizes_path, local: true do |form| %>

<% if @prize.errors.any? %>
<div id="error explanation">
  <h2>
    <% pluralize(@prize.errors.count, "error") %> prohibited this article from being saved:
    </h2>
    <ul>
      <% @prize.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
      </ul>
      </div>
      <% end %>
      </ul>
      </div>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

  <%= link_to 'Back', prizes_path %>

<% end %>

app/views/user/create.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/user/index.html.erb
<h1>Listing Users</h1>
<%# <%= link_to 'New prize', new_prize_path %> %>

<table>
  <tr>
    <th>Name</th>
    <th>Count</th>
    <th></th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.count %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/user/new.html.erb
<h1>New Prize</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1> Ticket </h1>
<%= link_to 'Prizes', controller: 'api/v1/prizes' %>
<%= link_to 'User', controller: 'api/v1/users' %>